server:
  port: 8086

spring:
  application:
    name: dubbo-goods-provider
  # DataBase
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/trade?useUnicode=true&characterEncoding=utf8

# Dubbo
dubbo:
  application:
    name: dubbo-goods-provider
    id: dubbo-goods-provider
  registry:
    adress: zookeeper//127.0.0.1:2181
  server: true
  protocol:
    name: dubbo
    prot: 20882

# Mybatis
mybatis:
  type-aliases-package: com.zy.shop.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

#RocketMQ
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: orderProducerGroup

mq:
  order:
    consumer:
      group:
        name: order_orderTopic_cancel_group
    topic: orderTopic
